## CONTENT 301 REDIRECTIONS

[[redirects]]
  from = "/docs/nlu/*/tutorial/"
  to = "/docs/rasa/user-guide/rasa-tutorial/"

[[redirects]]
  from = "/docs/nlu/*/evaluation/"
  to = "/docs/rasa/user-guide/testing-your-assistant/"

[[redirects]]
  from = "/docs/core/*/evaluation/"
  to = "/docs/rasa/user-guide/testing-your-assistant/"

[[redirects]]
  from = "/docs/core/*/tutorial_interactive_learning/"
  to = "/docs/rasa/core/interactive-learning/"

[[redirects]]
  from = "/docs/core/quickstart/"
  to = "/docs/rasa/user-guide/rasa-tutorial/"

[[redirects]]
  from = "/docs/core/installation/"
  to = "/docs/rasa/user-guide/installation/"

[[redirects]]
  from = "/docs/core/slots/"
  to = "/docs/rasa/core/slots/"

[[redirects]]
  from = "/docs/core/architecture/"
  to = "/docs/rasa/user-guide/architecture/"

[[redirects]]
  from = "/docs/core/connectors/"
  to = "/docs/rasa/user-guide/messaging-and-voice-channels/"

[[redirects]]
  from = "/docs/core/run-code-in-custom-actions/"
  to = "/docs/rasa/core/actions/"

[[redirects]]
  from = "/docs/core/slotfilling/"
  to = "/docs/rasa/core/forms/"

[[redirects]]
  from = "/docs/core/responses/"
  to = "/docs/rasa/core/responses/"

[[redirects]]
  from = "/docs/core/interactive_learning/"
  to = "/docs/rasa/core/interactive-learning/"

[[redirects]]
  from = "/docs/core/fallbacks/"
  to = "/docs/rasa/core/fallback-actions/"

[[redirects]]
  from = "/docs/core/policies/"
  to = "/docs/rasa/core/policies/"

[[redirects]]
  from = "/docs/core/evaluation/"
  to = "/docs/rasa/user-guide/testing-your-assistant/"

[[redirects]]
  from = "/docs/core/docker_walkthrough/"
  to = "/docs/rasa/user-guide/running-rasa-with-docker/"

[[redirects]]
  from = "/docs/core/domains/"
  to = "/docs/rasa/core/domains/"

[[redirects]]
  from = "/docs/core/stories/"
  to = "/docs/rasa/core/stories/"

[[redirects]]
  from = "/docs/core/api/slots_api/"
  to = "/docs/rasa/core/slots/"

[[redirects]]
  from = "/docs/core/server/"
  to = "/docs/rasa/pages/http-api/"

[[redirects]]
  from = "/docs/core/api/agent/"
  to = "/docs/rasa/core/about/"

[[redirects]]
  from = "/docs/core/api/events/"
  to = "/docs/rasa/api/events/"

[[redirects]]
  from = "/docs/core/api/tracker/"
  to = "/docs/rasa/api/tracker/"

[[redirects]]
  from = "/docs/core/api/interpreter/"
  to = "/docs/rasa/nlu/about/"

[[redirects]]
  from = "/docs/core/api/policy/"
  to = "/docs/rasa/core/policies/"

[[redirects]]
  from = "/docs/core/migrations/"
  to = "/docs/rasa/migration-guide/"

[[redirects]]
  from = "/docs/core/tracker_stores/"
  to = "/docs/rasa/api/tracker-stores/"

[[redirects]]
  from = "/docs/core/brokers/"
  to = "/docs/rasa/api/event-brokers/"

[[redirects]]
  from = "/docs/core/docker/"
  to = "/docs/rasa/user-guide/running-rasa-with-docker/"

[[redirects]]
  from = "/docs/nlu/quickstart/"
  to = "/docs/rasa/user-guide/rasa-tutorial/"

[[redirects]]
  from = "/docs/nlu/installation/"
  to = "/docs/rasa/user-guide/installation/"

[[redirects]]
  from = "/docs/nlu/choosing_pipeline/"
  to = "/docs/rasa/nlu/choosing-a-pipeline/"

[[redirects]]
  from = "/docs/nlu/languages/"
  to = "/docs/rasa/nlu/language-support/"

[[redirects]]
  from = "/docs/nlu/entities/"
  to = "/docs/rasa/nlu/entity-extraction/"

[[redirects]]
  from = "/docs/nlu/evaluation/"
  to = "/docs/rasa/user-guide/testing-your-assistant/"

[[redirects]]
  from = "/docs/nlu/fallback/"
  to = "/docs/rasa/nlu/about/"

[[redirects]]
  from = "/docs/nlu/dataformat/"
  to = "/docs/rasa/nlu/training-data-format/"

[[redirects]]
  from = "/docs/nlu/components/"
  to = "/docs/rasa/nlu/components/"

[[redirects]]
  from = "/docs/nlu/config/"
  to = "/docs/rasa/user-guide/running-the-server/"

[[redirects]]
  from = "/docs/nlu/http/"
  to = "/docs/rasa/pages/http-api/"

[[redirects]]
  from = "/docs/nlu/persist/"
  to = "/docs/rasa/user-guide/cloud-storage/"

[[redirects]]
  from = "/docs/nlu/endpoint_configuration/"
  to = "/docs/rasa/user-guide/running-the-server/"

[[redirects]]
  from = "/docs/nlu/docker/"
  to = "/docs/rasa/user-guide/running-rasa-with-docker/"

[[redirects]]
  from = "/docs/nlu/customcomponents/"
  to = "/docs/rasa/nlu/components/"

[[redirects]]
  from = "/docs/nlu/*"
  to = "/docs/rasa/nlu/about/"

[[redirects]]
  from = "/docs/core/*"
  to = "/docs/rasa/core/about/"

[[redirects]]
  from = "/docs/rasa/user-guide/running-rasa-with-docker/"
  to = "/docs/rasa/user-guide/docker/building-in-docker/"

[[redirects]]
  from = "/docs/rasa/user-guide/running-the-server/"
  to = "/docs/rasa/user-guide/configuring-http-api/"

[[redirects]]
  from = "/docs/rasa/user-guide/running-rasa-with-docker/#adding-custom-actions"
  to = "/docs/rasa/user-guide/how-to-deploy/#deploying-your-action-server"

[[redirects]]
  from = "/docs/rasa/user-guide/how-to-deploy/#adding-custom-actions"
  to = "/docs/rasa/user-guide/how-to-deploy/#deploying-your-action-server"

[[redirects]]
  from = "/docs/rasa/user-guide/how-to-deploy/#using-docker-compose-to-run-multiple-services"
  to = "/docs/rasa/user-guide/docker/deploying-in-docker-compose/"

[[redirects]]
  from = "/docs/rasa/user-guide/evaluating-models/"
  to = "/docs/rasa/user-guide/testing-your-assistant/"

[[redirects]]
  from = "/docs/rasa/user-guide/evaluating-models/#end-to-end-evaluation"
  to = "/docs/rasa/user-guide/testing-your-assistant/#end-to-end-testing"

[[redirects]]
  from = "/docs/rasa/user-guide/installation/"
  to = "/docs/rasa/installation/"

[[redirects]]
  from = "/docs/rasa/nlu/training-data-format/"
  to = "/docs/rasa/nlu-training-data/"

[[redirects]]
  from = "/docs/rasa/core/domains/"
  to = "/docs/rasa/domain/"

[[redirects]]
  from = "/docs/rasa/user-guide/testing-your-assistant/"
  to = "/docs/rasa/testing-your-assistant/"

[[redirects]]
  from = "/docs/rasa/user-guide/command-line-interface/"
  to = "/docs/rasa/command-line-interface/"

[[redirects]]
  from = "/docs/rasa/user-guide/setting-up-ci-cd/"
  to = "/docs/rasa/setting-up-ci-cd/"

[[redirects]]
  from = "/docs/rasa/user-guide/rasa-tutorial/"
  to = "/docs/rasa/prototype-an-assistant/"

[[redirects]]
  from = "/docs/rasa/user-guide/building-assistants/"
  to = "/docs/rasa/chitchat-faqs/"

[[redirects]]
  from = "/docs/rasa/core/stories/"
  to = "/docs/rasa/stories/"

[[redirects]]
  from = "/docs/rasa/user-guide/messaging-and-voice-channels/"
  to = "/docs/rasa/messaging-and-voice-channels/"

[[redirects]]
  from = "/docs/rasa/user-guide/configuring-http-api/"
  to = "/docs/rasa/http-api/"

[[redirects]]
  from = "/docs/rasa/user-guide/how-to-deploy/"
  to = "/docs/rasa/how-to-deploy/"

[[redirects]]
  from = "/docs/rasa/user-guide/cloud-storage/"
  to = "/docs/rasa/model-storage/"

[[redirects]]
  from = "/docs/rasa/nlu/choosing-a-pipeline/"
  to = "/docs/rasa/tuning-your-model/"

[[redirects]]
  from = "/docs/rasa/nlu/components/"
  to = "/docs/rasa/components/"

[[redirects]]
  from = "/docs/rasa/user-guide/connectors/*"
  to = "/docs/rasa/connectors/:splat"

[[redirects]]
  from = "/docs/rasa/nlu/entity-extraction/"
  to = "/docs/rasa/nlu-training-data/"

[[redirects]]
  from = "/docs/rasa/core/responses/"
  to = "/docs/rasa/domain/#responses"

[[redirects]]
  from = "/docs/rasa/core/actions/"
  to = "/docs/rasa/actions/"

[[redirects]]
  from = "/docs/rasa/core/reminders-and-external-events/"
  to = "/docs/rasa/reaching-out-to-user/"

[[redirects]]
  from = "/docs/rasa/core/policies/"
  to = "/docs/rasa/policies/"

[[redirects]]
  from = "/docs/rasa/core/slots/"
  to = "/docs/rasa/domain/#slots"

[[redirects]]
  from = "/docs/rasa/core/retrieval-actions/"
  to = "/docs/rasa/retrieval-actions/"

[[redirects]]
  from = "/docs/rasa/core/forms/"
  to = "/docs/rasa/forms/"

[[redirects]]
  from = "/docs/rasa/core/interactive-learning/"
  to = "/docs/rasa/writing-stories/#using-interactive-learning"

[[redirects]]
  from = "/docs/rasa/core/fallback-actions/"
  to = "/docs/rasa/fallback-handoff/#fallbacks"

[[redirects]]
  from = "/docs/rasa/dialogue-elements/small-talk/"
  to = "/docs/rasa/chitchat-faqs/"

[[redirects]]
  from = "/docs/rasa/api/action-server/"
  to = "/docs/rasa/pages/action-server-api/"

[[redirects]]
  from = "/docs/rasa/api/http-api/"
  to = "/docs/rasa/pages/http-api/"

[[redirects]]
  from = "/docs/rasa/api/jupyter-notebooks/"
  to = "/docs/rasa/jupyter-notebooks/"

[[redirects]]
  from = "/docs/rasa/api/custom-nlu-components/"
  to = "/docs/rasa/components/#custom-components"

[[redirects]]
  from = "/docs/rasa/api/tracker-stores/"
  to = "/docs/rasa/tracker-stores/"

[[redirects]]
  from = "/docs/rasa/api/event-brokers/"
  to = "/docs/rasa/event-brokers/"

[[redirects]]
  from = "/docs/rasa/api/lock-stores/"
  to = "/docs/rasa/lock-stores/"

[[redirects]]
  from = "/docs/rasa/api/training-data-importers/"
  to = "/docs/rasa/training-data-importers/"

[[redirects]]
  from = "/docs/rasa/retrieval-actions"
  to = "/docs/rasa/chitchat-faqs/"

[[redirects]]
  from = "/docs/rasa/prototype-an-assistant"
  to = "/docs/rasa/playground/"

# FIXME: this may conflict with version URL structure
[[redirects]]
  from = "/docs/rasa/next/*"
  to = "/docs/rasa/:splat"
  status = 301
  force = true

# FIXME: this requires some feedback as to the 404, like in the website
[[redirects]]
  from = "/docs/rasa/*"
  to = "/docs/rasa/index.html"
  status = 404
